repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --profile black src tests
        language: python
        types: [python]
      - id: black
        name: black
        entry: black src tests
        language: python
        types: [python]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        stages: [push]
